#!/bin/bash
while [ "$1" != "" ]
do
    case "$1" in
        backend)
            mkdir -p ./tmp/{db,data,cache,logs}
            docker-compose -f docker/docker-compose.dev.yml run -p 3000:3000 backend bash
            ;;
        down)
            docker-compose -f docker/docker-compose.dev.yml down
            ;;
        build)
            cp ./docker/.dockerignore ./
            cp ./docker/Dockerfile ./
            docker build -t ts-backend:latest .
            rm ./.dockerignore ./Dockerfile
            ;;
        -h | --help)
            echo $"Usage: $0 {backend|down|build}"
            exit 1
            ;;
    esac
    shift
done